In [514]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import export_graphviz, DecisionTreeClassifier as DT
from sklearn import metrics
import graphviz
import numpy as np

In [515]:
#Load the dataset
data = pd.read_csv('glass.csv')

Q2-a

In [522]:
#PREPROCESSING

#select an output class and feature classes
x_ = data.iloc[:,0:9]
y_ = data['Type']

#label encoding(unnecessary)
#from sklearn import preprocessing
#lblecd = preprocessing.LabelEncoder()
#y = lblecd.fit_transform(y_)

#form the feature array(unnecessary)
#x = x_.values

#split into train/test set w/ the proportion of 141(66%):73(34%)
#configure the shuffle = False, the training set would be as same as Weka
train_x , test_x, train_lbl , test_lbl = train_test_split(x_, y_, test_size = 0.34, shuffle = False)

Q2-b

In [523]:
#MODELING
clf = DT(criterion = 'entropy', 
        max_depth = 3,
        max_leaf_nodes = 4,)
clf.fit(train_x, train_lbl)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=4, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [529]:
#PREDICTING&TESTING
pred1 = clf.predict(train_x)
pred2 = clf.predict(test_x)

print('acc(training set): ' + str(metrics.accuracy_score(train_lbl, pred1)))
print('acc(testing set): ' + str(metrics.accuracy_score(test_lbl, pred2)))

acc(training set): 0.6524822695035462
acc(testing set): 0.6164383561643836


In [530]:
a = clf.classes_ 
new = np.append(a, 'None')
b[3], b[4], b[5] ,b[6] = 'None', a[3], a[5], a[4]

#check out the confusion matrix, and reorder the attribute according to weka
print(metrics.confusion_matrix(test_lbl, pred2, labels = b))

[[21  1  0  0  0  0  0]
 [10 17  0  0  0  0  1]
 [ 3  2  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  5  0  0  0  0  0]
 [ 0  1  0  0  0  0  3]
 [ 0  2  0  0  0  0  7]]


Q2-c

In [531]:
#VISUALIZING

def visualize_dt(clf_, name):
    dot_data = tree.export_graphviz(clf_, out_file = None)
    graph = graphviz.Source(dot_data)
    graph.render(str(name))
    
def acc_dt(clf_):
    clf_.fit(train_x, train_lbl)
    prediction = clf_.predict(test_x)
    print('Accuracy: ' + str(metrics.accuracy_score(test_lbl, prediction)))
    
# Origianl DT
visualize_dt(clf, 0)

Q2-d

In [534]:
#IMPROVEMENT

# I. Increase the max_leaf_nodes => 1.pdf
clf_mln = DT(criterion = 'entropy', 
        max_depth = 3,
        max_leaf_nodes = 10)

acc_dt(clf_mln)
visualize_dt(clf_mln, 1)

# II. Increase max_depth => 2.pdf
clf_md = DT(criterion = 'entropy', 
        max_depth = 6,
        max_leaf_nodes = 10)

acc_dt(clf_md)
visualize_dt(clf_md, 2)

# III. Increase min_samples_leaf => 3.pdf
clf_msl = DT(criterion = 'entropy', 
        max_depth = 6,
        max_leaf_nodes = 10,
        min_samples_leaf = 5)

acc_dt(clf_msl)
visualize_dt(clf_msl, 3)

Accuracy: 0.6301369863013698
Accuracy: 0.6575342465753424
Accuracy: 0.684931506849315
